In [1]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [2]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [3]:
import numpy as np
np.set_printoptions(linewidth=200)
import matplotlib.pyplot as plt
plt.imshow(train_images[0])
print(train_labels[0])
print(train_images[0])


Bad key "text.kerning_factor" on line 4 in
/home/vadim/anaconda3/envs/fastai/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution


9
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0   0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62  54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134 144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178 107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216 216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 232 233 229 223 

In [4]:
train_images = train_images / 255.0
test_images = test_images / 255.0

In [ ]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation=tf.nn.relu),
    keras.layers.Dense(10, activation= tf.nn.softmax)
])

In [12]:
model.compile(optimizer = tf.optimizers.Adam(),
             loss = "sparse_categorical_crossentropy",
             metrics=["accuracy"])

model.fit(train_images, train_labels, epochs = 10)

Epoch 1/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2818 - accuracy: 0.8963
Epoch 2/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2677 - accuracy: 0.8998
Epoch 3/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2574 - accuracy: 0.9037
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2469 - accuracy: 0.9074
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2368 - accuracy: 0.9108
Epoch 6/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2310 - accuracy: 0.9137
Epoch 7/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2229 - accuracy: 0.9167
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2154 - accuracy: 0.9180
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2085 - accuracy: 0.9214
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.205

In [16]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 1ms/step - loss: 0.0718


0.07179233431816101

In [10]:
classifications = model.predict(test_images)
print(classifications[0])

[5.6618715e-05 1.9437513e-07 7.6850677e-07 1.8791071e-07 1.0807345e-05 1.9154221e-02 3.2972455e-06 1.4793235e-02 7.2951916e-05 9.6590769e-01]


In [11]:
print(test_labels[0])

9


In [14]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(training_images, training_labels) ,  (test_images, test_labels) = mnist.load_data()

training_images = training_images/255.0
test_images = test_images/255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(1024, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy')

model.fit(training_images, training_labels, epochs=5)

model.evaluate(test_images, test_labels)

classifications = model.predict(test_images)

print(classifications[0])
print(test_labels[0])

11493376/11490434 [==============================] - 1s 0us/step
Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1832
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0739
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0495
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0344
Epoch 5/5
313/313 [==============================] - 0s 1ms/step - loss: 0.0718
[3.3861165e-09 2.0602718e-10 3.4871210e-08 1.0103530e-07 2.0579623e-14 7.6710881e-11 1.2188495e-13 9.9999988e-01 3.8832240e-09 7.7679916e-09]
7


In [15]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 1ms/step - loss: 0.0718


0.07179233431816101

In [17]:
import tensorflow as tf
print(tf.__version__)

mnist = tf.keras.datasets.mnist

(training_images, training_labels) ,  (test_images, test_labels) = mnist.load_data()

training_images = training_images/255.0
test_images = test_images/255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(512, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(256, activation=tf.nn.relu),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])

model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy')

model.fit(training_images, training_labels, epochs=5)

model.evaluate(test_images, test_labels)

classifications = model.predict(test_images)

print(classifications[0])
print(test_labels[0])

2.2.0
Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1864
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0799
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0527
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0420
Epoch 5/5
313/313 [==============================] - 0s 1ms/step - loss: 0.0884
[2.3115874e-11 1.0660378e-09 1.1191164e-07 1.8886270e-07 3.6137988e-11 6.1881378e-10 9.5277887e-16 9.9999797e-01 1.7914750e-09 1.6668132e-06]
7


In [18]:
import tensorflow as tf
print(tf.__version__)
mnist = tf.keras.datasets.mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
training_images=training_images
test_images=test_images
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
model.fit(training_images, training_labels, epochs=5)
model.evaluate(test_images, test_labels)
classifications = model.predict(test_images)
print(classifications[0])
print(test_labels[0])

2.2.0
Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 2.6606
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3426
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3007
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2826
Epoch 5/5
313/313 [==============================] - 0s 1ms/step - loss: 0.2991
[0.0000000e+00 9.8076591e-25 7.2702218e-24 5.4351364e-26 0.0000000e+00 1.7681144e-34 0.0000000e+00 1.0000000e+00 0.0000000e+00 1.1317920e-30]
7


In [19]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 1ms/step - loss: 0.2991


0.29909807443618774

In [20]:
import tensorflow as tf

class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if (logs.get("loss")<0.4):
            print("\nReached 60% acuracy so cancelling training")
            self.model.stop_training = True
callbacks = myCallback()
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()
training_images=training_images/255.0
test_images=test_images/255.0
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')
model.fit(training_images, training_labels, epochs=5, callbacks=[callbacks])


Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4730
Epoch 2/5
1841/1875 [============================>.] - ETA: 0s - loss: 0.3554
Reached 60% acuracy so cancelling training
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3555


In [21]:
model.evaluate(test_images, test_labels)

313/313 [==============================] - 0s 1ms/step - loss: 0.3924


0.39239734411239624